version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "4318:4318"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - otelcol

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.128.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./collector-contrib.yaml:/etc/otelcol/config.yaml:ro
    expose:
      - "4318"
      - "13133"